# Generated by Django 4.1.3 on 2022-12-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsstory_options_alter_newsstory_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ('pub_date',)},
        ),
    ]
